version: '3'
services:

  namenode:
    image: kilfu0701/hadoop-namenode:3.3.2-java8
    container_name: namenode
    volumes:
      - ./volumes/hive/hdfs/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=hive
    env_file:
      - ./env/hadoop-hive.env
    ports:
      - "9870:9870"

  datanode:
    image: kilfu0701/hadoop-datanode:3.3.2-java8
    container_name: datanode
    volumes:
      - ./volumes/hive/hdfs/datanode:/hadoop/dfs/data
    env_file:
      - ./env/hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    depends_on:
      - namenode
    ports:
      - "9864:9864"

  resourcemanager:
    image: kilfu0701/hadoop-resourcemanager:3.3.2-java8
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864"
    env_file:
      - ./env/hadoop.env

  nodemanager1:
    image: kilfu0701/hadoop-nodemanager:3.3.2-java8
    container_name: nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./env/hadoop.env

  historyserver:
    image: kilfu0701/hadoop-historyserver:3.3.2-java8
    container_name: historyserver
    volumes:
      - ./volumes/hbase/hadoop_historyserver:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./env/hadoop.env

  hive-server: # hive-3.1.3
    build: ./docker.config/hive-server/
    container_name: hive-server
    volumes:
      - ./src/tables:/tables
      - ./src/sampleauth.jar:/opt/hive/lib/sampleauth.jar
    env_file:
      - ./env/hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
      JAVA_OPTS: -Xmx4g -Xms4g -XX:MaxPermSize=4g -XX:PermSize=4g
      HADOOP_HEAPSIZE: 4096
      #HIVE_SERVER2_THRIFT_PORT: 51000
    depends_on:
      - hive-metastore
    ports:
      - '10000:10000'
    shm_size: '4gb'
    restart: always

  hive-metastore: # hive-3.1.3
    build: ./docker.config/hive-metastore/
    container_name: hive-metastore
    env_file:
      - ./env/hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 hive-metastore-postgresql:5432"
    depends_on:
      - hive-metastore-postgresql
    ports:
      - "9083:9083"

  hive-metastore-postgresql:
    build: ./docker.config/hive-metastore-postgresql/
    platform: linux/arm64
    container_name: hive-metastore-postgresql
    volumes:
      - ./volumes/hive/metastore-postgresql/postgresql/data:/var/lib/postgresql/data
    depends_on:
      - datanode
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  hive-python3:
    restart: always
    build: ./docker.config/hive-python3/
    container_name: 'hive-python3'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./src/hive-py3:/root/hive-py3

  hbase-java8:
    restart: always
    build: ./docker.config/hbase-java8/
    container_name: 'hbase-java8'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./src/hbase-java8-api:/root/hbase-java8-api
    ports:
      - 51080:80

  hbase:
    image: bde2020/hbase-standalone:1.0.0-hbase1.2.6
    container_name: hbase
    volumes:
      - ./volumes/hbase/hbase_data:/hbase-data
      - ./volumes/hbase/hbase_zookeeper_data:/zookeeper-data
    ports:
      - 16000:16000
      - 16010:16010
      - 16020:16020
      - 16030:16030
      - 2888:2888
      - 3888:3888
      - 2181:2181
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864"
    env_file:
      - ./env/hbase-standalone.env

networks:
  backend:
    driver: bridge
